version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: web-research-agent
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - ENV=production
      - HUGGINGFACE_API_TOKEN=your_huggingface_token_here
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  worker:
    build: .
    container_name: celery-worker
    depends_on:
      - redis
    environment:
      - ENV=production
      - HUGGINGFACE_API_TOKEN=your_huggingface_token_here
    command: celery -A worker.celery worker --loglevel=info
